# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
  # Allow external triggers
  repository_dispatch:
    types:
      - webhook

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-18.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: release-downloader
        # You may pin to the exact commit or the version.
        # uses: robinraju/release-downloader@95181030e3b4d574d027e8f4bb7d97fc62331c35
        uses: robinraju/release-downloader@v1.2
        with:
          repository: SteamRE/DepotDownloader
          latest: true
          # Name of the file to download (use '*' to download all assets other than tarball or zipball)
          fileName: '*'

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.8.2

      # Runs a single command using the runners shell
      - name: Unzip DepotDownloader
        run: sudo apt install unzip && unzip -d depotdownloader *.zip && dotnet depotdownloader/DepotDownloader.dll
      
      
        
      
